// Generated from backend/src/modules/access/permissions.ts by
// scripts/generatePermissionKeys.ts. Do not edit by hand.

export const permissionKeys = [
  "users.view",
  "users.create",
  "users.update",
  "users.activate",
  "users.assign_roles",
  "users.reset_password",
  "roles.view",
  "roles.create",
  "roles.update",
  "roles.activate",
  "roles.assign_permissions",
  "products.view",
  "products.create",
  "products.update",
  "products.activate",
  "categories.view",
  "categories.manage",
  "raw_materials.view",
  "raw_materials.create",
  "raw_materials.update",
  "raw_materials.activate",
  "units.view",
  "units.manage",
  "inventory.view",
  "inventory.movements.view",
  "inventory.adjust",
  "inventory.opening_stock",
  "suppliers.view",
  "suppliers.create",
  "suppliers.update",
  "purchases.view",
  "purchases.create",
  "purchases.post",
  "purchases.cancel",
  "supplier_payments.view",
  "supplier_payments.create",
  "supplier_balances.view",
  "pos.access",
  "pos.open_session",
  "pos.sell",
  "pos.credit_sale",
  "pos.cancel_sale",
  "pos.close_session",
  "orders.view",
  "orders.create",
  "orders.update",
  "orders.change_status",
  "orders.cancel",
  "orders.complete",
  "customers.view",
  "customers.create",
  "customers.update",
  "customer_balances.view",
  "customer_payments.view",
  "customer_payments.create",
  "distributors.view",
  "distributors.create",
  "distributors.update",
  "distribution.dispatch",
  "distribution.settle",
  "distribution.direct_sale",
  "distribution.custody.view",
  "distribution.balances.view",
  "distributor_payments.view",
  "distributor_payments.create",
  "expenses.view",
  "expenses.create",
  "expenses.cancel",
  "expense_categories.manage",
  "simulations.view",
  "simulations.create",
  "simulations.update",
  "simulations.delete",
  "audit.view",
] as const;

export type PermissionKey = (typeof permissionKeys)[number];

export const permissionModules = [
  "Utilisateurs",
  "Rôles",
  "Produits",
  "Catégories",
  "Matières premières",
  "Unités",
  "Stock",
  "Fournisseurs",
  "Achats",
  "Paiements fournisseurs",
  "Soldes fournisseurs",
  "Caisse",
  "Commandes client",
  "Clients",
  "Soldes clients",
  "Paiements clients",
  "Distributeurs",
  "Distribution",
  "Paiements distributeurs",
  "Dépenses",
  "Catégories de dépenses",
  "Simulations",
  "Audit",
] as const;
