import * as access from "../modules/access/access.routes.js";
import * as audit from "../modules/audit/audit.routes.js";
import * as auth from "../modules/auth/auth.routes.js";
import * as catalog from "../modules/catalog/catalog.routes.js";
import * as customers from "../modules/customers/customers.routes.js";
import * as distribution from "../modules/distribution/distribution.routes.js";
import * as expenses from "../modules/expenses/expenses.routes.js";
import * as home from "../modules/home/home.routes.js";
import * as inventory from "../modules/inventory/inventory.routes.js";
import * as orders from "../modules/orders/orders.routes.js";
import * as pos from "../modules/pos/pos.routes.js";
import * as procurement from "../modules/procurement/procurement.routes.js";
import * as simulation from "../modules/simulation/simulation.routes.js";
import { operation, type ApiOperation } from "./registry.js";

/// The `/api/v1` catalogue, one record per mounted route, grouped the way
/// the routers are mounted in `app.ts`. Paths are relative to `/api/v1`.

const healthOperations: ApiOperation[] = [
  operation({
    method: "get",
    path: "/health",
    operationId: "health.ready",
    summary: "Readiness: service and database status",
    tag: "health",
    public: true,
  }),
  operation({
    method: "get",
    path: "/health/ready",
    operationId: "health.readyAlias",
    summary: "Readiness (alias)",
    tag: "health",
    public: true,
  }),
  operation({
    method: "get",
    path: "/health/live",
    operationId: "health.live",
    summary: "Liveness: process is up",
    tag: "health",
    public: true,
  }),
];

const authOperations: ApiOperation[] = [
  operation({
    method: "post",
    path: "/auth/login",
    operationId: "auth.login",
    summary: "Open a session (rate limited)",
    tag: "auth",
    public: true,
    body: auth.loginSchema,
    dataKey: "user",
    status: 200,
  }),
  operation({
    method: "get",
    path: "/auth/me",
    operationId: "auth.me",
    summary: "Current user and effective permissions",
    tag: "auth",
    permissions: [],
    dataKey: "user",
  }),
  operation({
    method: "post",
    path: "/auth/logout",
    operationId: "auth.logout",
    summary: "Close the current session",
    tag: "auth",
    permissions: [],
  }),
];

const accessOperations: ApiOperation[] = [
  operation({
    method: "get",
    path: "/access/permissions",
    operationId: "access.listPermissions",
    summary: "Permission catalogue, flat and grouped by module",
    tag: "access",
    permissions: ["roles.view"],
  }),
  operation({
    method: "get",
    path: "/access/roles",
    operationId: "access.listRoles",
    summary: "Roles with permission and user counts",
    tag: "access",
    permissions: ["roles.view"],
    dataKey: "roles",
  }),
  operation({
    method: "post",
    path: "/access/roles",
    operationId: "access.createRole",
    summary: "Create a role",
    tag: "access",
    permissions: ["roles.create"],
    body: access.createRoleSchema,
    status: 201,
    dataKey: "role",
  }),
  operation({
    method: "get",
    path: "/access/roles/{roleId}",
    operationId: "access.getRole",
    summary: "Role detail",
    tag: "access",
    permissions: ["roles.view"],
    dataKey: "role",
  }),
  operation({
    method: "patch",
    path: "/access/roles/{roleId}",
    operationId: "access.updateRole",
    summary: "Rename, describe, or activate a role",
    tag: "access",
    permissions: ["roles.update"],
    body: access.updateRoleSchema,
    dataKey: "role",
  }),
  operation({
    method: "put",
    path: "/access/roles/{roleId}/permissions",
    operationId: "access.replaceRolePermissions",
    summary: "Replace the permissions of a role",
    tag: "access",
    permissions: ["roles.assign_permissions"],
    body: access.replacePermissionsSchema,
    dataKey: "role",
  }),
  operation({
    method: "get",
    path: "/access/users",
    operationId: "access.listUsers",
    summary: "Users, paginated and filterable",
    tag: "access",
    permissions: ["users.view"],
    query: access.userListQuerySchema,
    list: true,
  }),
  operation({
    method: "post",
    path: "/access/users",
    operationId: "access.createUser",
    summary: "Create a user with a temporary password",
    tag: "access",
    permissions: ["users.create"],
    body: access.createUserSchema,
    status: 201,
    dataKey: "user",
  }),
  operation({
    method: "get",
    path: "/access/users/{userId}",
    operationId: "access.getUser",
    summary: "User detail",
    tag: "access",
    permissions: ["users.view"],
    dataKey: "user",
  }),
  operation({
    method: "patch",
    path: "/access/users/{userId}",
    operationId: "access.updateUser",
    summary: "Change the display name or e-mail of a user",
    tag: "access",
    permissions: ["users.update"],
    body: access.updateUserSchema,
    dataKey: "user",
  }),
  operation({
    method: "post",
    path: "/access/users/{userId}/password-reset",
    operationId: "access.resetPassword",
    summary: "Set a temporary password and end the user's sessions",
    tag: "access",
    permissions: ["users.reset_password"],
    body: access.passwordResetSchema,
    dataKey: "user",
  }),
  operation({
    method: "put",
    path: "/access/users/{userId}/roles",
    operationId: "access.replaceUserRoles",
    summary: "Replace the roles of a user",
    tag: "access",
    permissions: ["users.assign_roles"],
    body: access.replaceUserRolesSchema,
    dataKey: "user",
  }),
  operation({
    method: "patch",
    path: "/access/users/{userId}/activation",
    operationId: "access.setUserActivation",
    summary: "Activate or deactivate a user",
    tag: "access",
    permissions: ["users.activate"],
    body: access.userActivationSchema,
    dataKey: "user",
  }),
];

const auditOperations: ApiOperation[] = [
  operation({
    method: "get",
    path: "/audit-events",
    operationId: "audit.listEvents",
    summary: "Audit events with French labels",
    tag: "audit",
    permissions: ["audit.view"],
    query: audit.listQuerySchema,
    list: true,
  }),
  operation({
    method: "get",
    path: "/audit-filters",
    operationId: "audit.listFilters",
    summary: "Distinct actions and entities for the filters",
    tag: "audit",
    permissions: ["audit.view"],
  }),
];

const catalogOperations: ApiOperation[] = [
  operation({
    method: "get",
    path: "/catalog/units",
    operationId: "catalog.listUnits",
    summary: "Units",
    tag: "catalog",
    permissions: ["units.view"],
    query: catalog.listQuerySchema,
    list: true,
  }),
  operation({
    method: "post",
    path: "/catalog/units",
    operationId: "catalog.createUnit",
    summary: "Create a unit",
    tag: "catalog",
    permissions: ["units.manage"],
    body: catalog.createUnitSchema,
    status: 201,
    dataKey: "unit",
  }),
  operation({
    method: "patch",
    path: "/catalog/units/{unitId}",
    operationId: "catalog.updateUnit",
    summary: "Update a unit",
    tag: "catalog",
    permissions: ["units.manage"],
    body: catalog.updateUnitSchema,
    dataKey: "unit",
  }),
  operation({
    method: "get",
    path: "/catalog/categories",
    operationId: "catalog.listCategories",
    summary: "Product categories",
    tag: "catalog",
    permissions: ["categories.view"],
    query: catalog.listQuerySchema,
    list: true,
  }),
  operation({
    method: "post",
    path: "/catalog/categories",
    operationId: "catalog.createCategory",
    summary: "Create a product category",
    tag: "catalog",
    permissions: ["categories.manage"],
    body: catalog.createCategorySchema,
    status: 201,
    dataKey: "category",
  }),
  operation({
    method: "patch",
    path: "/catalog/categories/{categoryId}",
    operationId: "catalog.updateCategory",
    summary: "Update a product category",
    tag: "catalog",
    permissions: ["categories.manage"],
    body: catalog.updateCategorySchema,
    dataKey: "category",
  }),
  operation({
    method: "get",
    path: "/catalog/raw-materials",
    operationId: "catalog.listRawMaterials",
    summary: "Raw materials",
    tag: "catalog",
    permissions: ["raw_materials.view"],
    query: catalog.listQuerySchema,
    list: true,
  }),
  operation({
    method: "post",
    path: "/catalog/raw-materials",
    operationId: "catalog.createRawMaterial",
    summary: "Create a raw material",
    tag: "catalog",
    permissions: ["raw_materials.create"],
    body: catalog.createRawMaterialSchema,
    status: 201,
    dataKey: "rawMaterial",
  }),
  operation({
    method: "get",
    path: "/catalog/raw-materials/{rawMaterialId}",
    operationId: "catalog.getRawMaterial",
    summary: "Raw material detail",
    tag: "catalog",
    permissions: ["raw_materials.view"],
    dataKey: "rawMaterial",
  }),
  operation({
    method: "patch",
    path: "/catalog/raw-materials/{rawMaterialId}",
    operationId: "catalog.updateRawMaterial",
    summary: "Update a raw material",
    tag: "catalog",
    permissions: ["raw_materials.update"],
    body: catalog.updateRawMaterialSchema,
    dataKey: "rawMaterial",
  }),
  operation({
    method: "patch",
    path: "/catalog/raw-materials/{rawMaterialId}/activation",
    operationId: "catalog.setRawMaterialActivation",
    summary: "Activate or deactivate a raw material",
    tag: "catalog",
    permissions: ["raw_materials.activate"],
    body: catalog.activationSchema,
    dataKey: "rawMaterial",
  }),
  operation({
    method: "put",
    path: "/catalog/raw-materials/{rawMaterialId}/conversions",
    operationId: "catalog.replaceRawMaterialConversions",
    summary: "Replace the unit conversions of a raw material",
    tag: "catalog",
    permissions: ["raw_materials.update"],
    body: catalog.replaceRawMaterialConversionsSchema,
    dataKey: "rawMaterial",
  }),
  operation({
    method: "get",
    path: "/catalog/products",
    operationId: "catalog.listProducts",
    summary: "Products",
    tag: "catalog",
    permissions: ["products.view"],
    query: catalog.productListQuerySchema,
    list: true,
  }),
  operation({
    method: "post",
    path: "/catalog/products",
    operationId: "catalog.createProduct",
    summary: "Create a product",
    tag: "catalog",
    permissions: ["products.create"],
    body: catalog.createProductSchema,
    status: 201,
    dataKey: "product",
  }),
  operation({
    method: "get",
    path: "/catalog/products/{productId}",
    operationId: "catalog.getProduct",
    summary: "Product detail",
    tag: "catalog",
    permissions: ["products.view"],
    dataKey: "product",
  }),
  operation({
    method: "patch",
    path: "/catalog/products/{productId}",
    operationId: "catalog.updateProduct",
    summary: "Update a product",
    tag: "catalog",
    permissions: ["products.update"],
    body: catalog.updateProductSchema,
    dataKey: "product",
  }),
  operation({
    method: "patch",
    path: "/catalog/products/{productId}/activation",
    operationId: "catalog.setProductActivation",
    summary: "Activate or deactivate a product",
    tag: "catalog",
    permissions: ["products.activate"],
    body: catalog.activationSchema,
    dataKey: "product",
  }),
];

const customerOperations: ApiOperation[] = [
  operation({
    method: "get",
    path: "/customers",
    operationId: "customers.list",
    summary: "Customers",
    tag: "customers",
    permissions: ["customers.view"],
    query: customers.listQuerySchema,
    list: true,
  }),
  operation({
    method: "post",
    path: "/customers",
    operationId: "customers.create",
    summary: "Create a customer",
    tag: "customers",
    permissions: ["customers.create"],
    body: customers.createCustomerSchema,
    status: 201,
    dataKey: "customer",
  }),
  operation({
    method: "get",
    path: "/customers/{customerId}",
    operationId: "customers.get",
    summary: "Customer detail with balances",
    tag: "customers",
    permissions: ["customers.view"],
    dataKey: "customer",
  }),
  operation({
    method: "patch",
    path: "/customers/{customerId}",
    operationId: "customers.update",
    summary: "Update a customer",
    tag: "customers",
    permissions: ["customers.update"],
    body: customers.updateCustomerSchema,
    dataKey: "customer",
  }),
  operation({
    method: "get",
    path: "/customers/{customerId}/statement",
    operationId: "customers.statement",
    summary: "Customer statement, cursor-paged with balances",
    tag: "customers",
    permissions: ["customer_balances.view"],
    query: customers.statementQuerySchema,
    statement: true,
  }),
  operation({
    method: "get",
    path: "/customer-balances",
    operationId: "customers.listBalances",
    summary: "Customer receivable balances",
    tag: "customers",
    permissions: ["customer_balances.view"],
    query: customers.balanceListQuerySchema,
    list: true,
  }),
  operation({
    method: "get",
    path: "/customer-payments",
    operationId: "customers.listPayments",
    summary: "Customer payments",
    tag: "customers",
    permissions: ["customer_payments.view"],
    query: customers.paymentListQuerySchema,
    list: true,
  }),
  operation({
    method: "post",
    path: "/customer-payments",
    operationId: "customers.createPayment",
    summary: "Record a customer payment",
    tag: "customers",
    permissions: ["customer_payments.create"],
    body: customers.createCustomerPaymentSchema,
    idempotent: true,
    status: 201,
    dataKey: "payment",
  }),
];

const distributionOperations: ApiOperation[] = [
  operation({
    method: "get",
    path: "/distributors",
    operationId: "distribution.listDistributors",
    summary: "Distributors",
    tag: "distribution",
    permissions: ["distributors.view"],
    query: distribution.listQuerySchema,
    list: true,
  }),
  operation({
    method: "post",
    path: "/distributors",
    operationId: "distribution.createDistributor",
    summary: "Create a distributor",
    tag: "distribution",
    permissions: ["distributors.create"],
    body: distribution.createDistributorSchema,
    status: 201,
    dataKey: "distributor",
  }),
  operation({
    method: "get",
    path: "/distributors/{distributorId}",
    operationId: "distribution.getDistributor",
    summary: "Distributor detail with balance and custody",
    tag: "distribution",
    permissions: ["distributors.view"],
    dataKey: "distributor",
  }),
  operation({
    method: "patch",
    path: "/distributors/{distributorId}",
    operationId: "distribution.updateDistributor",
    summary: "Update a distributor",
    tag: "distribution",
    permissions: ["distributors.update"],
    body: distribution.updateDistributorSchema,
    dataKey: "distributor",
  }),
  operation({
    method: "get",
    path: "/distributors/{distributorId}/statement",
    operationId: "distribution.statement",
    summary: "Distributor statement, cursor-paged with balances",
    tag: "distribution",
    permissions: ["distribution.balances.view"],
    query: distribution.statementQuerySchema,
    statement: true,
  }),
  operation({
    method: "post",
    path: "/distributor-sales",
    operationId: "distribution.directSale",
    summary: "Post a direct sale to a distributor",
    tag: "distribution",
    permissions: ["distribution.direct_sale"],
    body: distribution.directSaleSchema,
    idempotent: true,
    status: 201,
    dataKey: "sale",
  }),
  operation({
    method: "get",
    path: "/distributor-dispatches",
    operationId: "distribution.listDispatches",
    summary: "Consignment dispatches",
    tag: "distribution",
    permissions: ["distribution.custody.view"],
    query: distribution.dispatchListQuerySchema,
    list: true,
  }),
  operation({
    method: "post",
    path: "/distributor-dispatches",
    operationId: "distribution.dispatch",
    summary: "Post a consignment dispatch",
    tag: "distribution",
    permissions: ["distribution.dispatch"],
    body: distribution.dispatchSchema,
    idempotent: true,
    status: 201,
    dataKey: "dispatch",
  }),
  operation({
    method: "get",
    path: "/distributor-dispatches/{dispatchId}",
    operationId: "distribution.getDispatch",
    summary: "Dispatch detail",
    tag: "distribution",
    permissions: ["distribution.custody.view"],
    dataKey: "dispatch",
  }),
  operation({
    method: "get",
    path: "/distributor-settlements",
    operationId: "distribution.listSettlements",
    summary: "Consignment settlements",
    tag: "distribution",
    permissions: ["distribution.custody.view"],
    query: distribution.settlementListQuerySchema,
    list: true,
  }),
  operation({
    method: "post",
    path: "/distributor-settlements",
    operationId: "distribution.settle",
    summary: "Post a consignment settlement",
    tag: "distribution",
    permissions: ["distribution.settle"],
    body: distribution.settlementSchema,
    idempotent: true,
    status: 201,
    dataKey: "settlement",
  }),
  operation({
    method: "get",
    path: "/distributor-custody",
    operationId: "distribution.custody",
    summary: "Goods held by distributors",
    tag: "distribution",
    permissions: ["distribution.custody.view"],
    query: distribution.custodyQuerySchema,
  }),
  operation({
    method: "get",
    path: "/distributor-balances",
    operationId: "distribution.listBalances",
    summary: "Distributor balances",
    tag: "distribution",
    permissions: ["distribution.balances.view"],
    query: distribution.balanceListQuerySchema,
    list: true,
  }),
  operation({
    method: "get",
    path: "/distributor-payments",
    operationId: "distribution.listPayments",
    summary: "Distributor payments",
    tag: "distribution",
    permissions: ["distributor_payments.view"],
    query: distribution.paymentListQuerySchema,
    list: true,
  }),
  operation({
    method: "post",
    path: "/distributor-payments",
    operationId: "distribution.createPayment",
    summary: "Record a distributor payment",
    tag: "distribution",
    permissions: ["distributor_payments.create"],
    body: distribution.createPaymentSchema,
    idempotent: true,
    status: 201,
    dataKey: "payment",
  }),
];

const expenseOperations: ApiOperation[] = [
  operation({
    method: "get",
    path: "/expense-categories",
    operationId: "expenses.listCategories",
    summary: "Expense categories",
    tag: "expenses",
    permissions: ["expenses.view"],
    query: expenses.categoryListQuerySchema,
    list: true,
  }),
  operation({
    method: "post",
    path: "/expense-categories",
    operationId: "expenses.createCategory",
    summary: "Create an expense category",
    tag: "expenses",
    permissions: ["expense_categories.manage"],
    body: expenses.createCategorySchema,
    status: 201,
    dataKey: "expenseCategory",
  }),
  operation({
    method: "patch",
    path: "/expense-categories/{categoryId}",
    operationId: "expenses.updateCategory",
    summary: "Update an expense category",
    tag: "expenses",
    permissions: ["expense_categories.manage"],
    body: expenses.updateCategorySchema,
    dataKey: "expenseCategory",
  }),
  operation({
    method: "get",
    path: "/expenses",
    operationId: "expenses.list",
    summary: "Expenses",
    tag: "expenses",
    permissions: ["expenses.view"],
    query: expenses.expenseListQuerySchema,
    list: true,
  }),
  operation({
    method: "get",
    path: "/expense-totals",
    operationId: "expenses.totals",
    summary: "Expense totals for a period",
    tag: "expenses",
    permissions: ["expenses.view"],
    query: expenses.totalsQuerySchema,
  }),
  operation({
    method: "post",
    path: "/expenses",
    operationId: "expenses.create",
    summary: "Create a draft expense",
    tag: "expenses",
    permissions: ["expenses.create"],
    body: expenses.createExpenseSchema,
    status: 201,
    dataKey: "expense",
  }),
  operation({
    method: "get",
    path: "/expenses/{expenseId}",
    operationId: "expenses.get",
    summary: "Expense detail",
    tag: "expenses",
    permissions: ["expenses.view"],
    dataKey: "expense",
  }),
  operation({
    method: "patch",
    path: "/expenses/{expenseId}",
    operationId: "expenses.update",
    summary: "Update a draft expense",
    tag: "expenses",
    permissions: ["expenses.create"],
    body: expenses.updateExpenseSchema,
    dataKey: "expense",
  }),
  operation({
    method: "post",
    path: "/expenses/{expenseId}/post",
    operationId: "expenses.post",
    summary: "Post an expense",
    tag: "expenses",
    permissions: ["expenses.create"],
    body: expenses.postExpenseSchema,
    dataKey: "expense",
  }),
  operation({
    method: "post",
    path: "/expenses/{expenseId}/cancel",
    operationId: "expenses.cancel",
    summary: "Cancel an expense",
    tag: "expenses",
    permissions: ["expenses.cancel"],
    body: expenses.cancelExpenseSchema,
    dataKey: "expense",
  }),
];

const homeOperations: ApiOperation[] = [
  operation({
    method: "get",
    path: "/home/summary",
    operationId: "home.summary",
    summary: "Operational summary, one block per permission held",
    tag: "home",
    permissions: [],
    query: home.summaryQuerySchema,
    dataKey: "summary",
  }),
];

const inventoryOperations: ApiOperation[] = [
  operation({
    method: "get",
    path: "/inventory/balances",
    operationId: "inventory.balances",
    summary: "Stock balances per item",
    tag: "inventory",
    permissions: ["inventory.view"],
  }),
  operation({
    method: "get",
    path: "/inventory/movements",
    operationId: "inventory.listMovements",
    summary: "Stock movements",
    tag: "inventory",
    permissions: ["inventory.movements.view"],
    query: inventory.listQuerySchema,
    list: true,
  }),
  operation({
    method: "post",
    path: "/inventory/opening-stock",
    operationId: "inventory.openingStock",
    summary: "Record opening stock",
    tag: "inventory",
    permissions: ["inventory.opening_stock"],
    body: inventory.openingStockSchema,
    idempotent: true,
    status: 201,
    dataKey: "movement",
  }),
  operation({
    method: "post",
    path: "/inventory/adjustments",
    operationId: "inventory.adjust",
    summary: "Record a stock adjustment",
    tag: "inventory",
    permissions: ["inventory.adjust"],
    body: inventory.adjustmentSchema,
    idempotent: true,
    status: 201,
    dataKey: "movement",
  }),
];

const orderOperations: ApiOperation[] = [
  operation({
    method: "get",
    path: "/orders",
    operationId: "orders.list",
    summary: "Customer orders",
    tag: "orders",
    permissions: ["orders.view"],
    query: orders.listQuerySchema,
    list: true,
  }),
  operation({
    method: "post",
    path: "/orders",
    operationId: "orders.create",
    summary: "Create a customer order",
    tag: "orders",
    permissions: ["orders.create"],
    body: orders.createOrderSchema,
    idempotent: true,
    status: 201,
    dataKey: "order",
  }),
  operation({
    method: "get",
    path: "/orders/{orderId}",
    operationId: "orders.get",
    summary: "Order detail",
    tag: "orders",
    permissions: ["orders.view"],
    dataKey: "order",
  }),
  operation({
    method: "patch",
    path: "/orders/{orderId}",
    operationId: "orders.update",
    summary: "Update an order",
    tag: "orders",
    permissions: ["orders.update"],
    body: orders.updateOrderSchema,
    dataKey: "order",
  }),
  operation({
    method: "post",
    path: "/orders/{orderId}/status",
    operationId: "orders.changeStatus",
    summary: "Move an order along its workflow",
    tag: "orders",
    permissions: ["orders.change_status"],
    body: orders.changeStatusSchema,
    dataKey: "order",
  }),
  operation({
    method: "post",
    path: "/orders/{orderId}/advances",
    operationId: "orders.recordAdvance",
    summary: "Record an advance on an order",
    tag: "orders",
    permissions: ["orders.update", "customer_payments.create"],
    body: orders.advanceSchema,
    idempotent: true,
    status: 201,
    dataKey: "order",
  }),
  operation({
    method: "post",
    path: "/orders/{orderId}/complete",
    operationId: "orders.complete",
    summary: "Complete an order into a sale",
    tag: "orders",
    permissions: ["orders.complete"],
    body: orders.completeOrderSchema,
    idempotent: true,
    status: 201,
    dataKey: "order",
  }),
  operation({
    method: "post",
    path: "/orders/{orderId}/cancel",
    operationId: "orders.cancel",
    summary: "Cancel an order",
    tag: "orders",
    permissions: ["orders.cancel"],
    body: orders.cancelOrderSchema,
    idempotent: true,
    dataKey: "order",
  }),
];

const posOperations: ApiOperation[] = [
  operation({
    method: "get",
    path: "/pos/products",
    operationId: "pos.listProducts",
    summary: "Sellable products for the till",
    tag: "pos",
    permissions: ["pos.access"],
    query: pos.listQuerySchema,
    list: true,
  }),
  operation({
    method: "get",
    path: "/pos/customers",
    operationId: "pos.listCustomers",
    summary: "Customers for a credit sale or an order",
    tag: "pos",
    permissions: ["pos.credit_sale", "orders.create"],
    query: pos.listQuerySchema,
    list: true,
  }),
  operation({
    method: "get",
    path: "/pos/sessions",
    operationId: "pos.listSessions",
    summary: "Till sessions",
    tag: "pos",
    permissions: ["pos.access"],
    query: pos.sessionListQuerySchema,
    list: true,
  }),
  operation({
    method: "get",
    path: "/pos/sessions/current",
    operationId: "pos.currentSession",
    summary: "The open session, if any",
    tag: "pos",
    permissions: ["pos.access"],
    dataKey: "session",
  }),
  operation({
    method: "post",
    path: "/pos/sessions/open",
    operationId: "pos.openSession",
    summary: "Open a till session",
    tag: "pos",
    permissions: ["pos.open_session"],
    body: pos.openSessionSchema,
    idempotent: true,
    status: 201,
    dataKey: "session",
  }),
  operation({
    method: "get",
    path: "/pos/sessions/{sessionId}",
    operationId: "pos.getSession",
    summary: "Session detail with totals",
    tag: "pos",
    permissions: ["pos.access"],
    dataKey: "session",
  }),
  operation({
    method: "post",
    path: "/pos/sessions/{sessionId}/close",
    operationId: "pos.closeSession",
    summary: "Close a till session",
    tag: "pos",
    permissions: ["pos.close_session"],
    body: pos.closeSessionSchema,
    idempotent: true,
    status: 201,
    dataKey: "session",
  }),
  operation({
    method: "get",
    path: "/pos/sales",
    operationId: "pos.listSales",
    summary: "Sales",
    tag: "pos",
    permissions: ["pos.access"],
    query: pos.saleListQuerySchema,
    list: true,
  }),
  operation({
    method: "post",
    path: "/pos/sales",
    operationId: "pos.postSale",
    summary: "Post a sale",
    tag: "pos",
    permissions: ["pos.sell"],
    body: pos.postSaleSchema,
    idempotent: true,
    status: 201,
    dataKey: "sale",
  }),
  operation({
    method: "get",
    path: "/pos/sales/{saleId}",
    operationId: "pos.getSale",
    summary: "Sale detail",
    tag: "pos",
    permissions: ["pos.access"],
    dataKey: "sale",
  }),
];

const procurementOperations: ApiOperation[] = [
  operation({
    method: "get",
    path: "/procurement/suppliers",
    operationId: "procurement.listSuppliers",
    summary: "Suppliers",
    tag: "procurement",
    permissions: ["suppliers.view"],
    query: procurement.listQuerySchema,
    list: true,
  }),
  operation({
    method: "post",
    path: "/procurement/suppliers",
    operationId: "procurement.createSupplier",
    summary: "Create a supplier",
    tag: "procurement",
    permissions: ["suppliers.create"],
    body: procurement.createSupplierSchema,
    status: 201,
    dataKey: "supplier",
  }),
  operation({
    method: "get",
    path: "/procurement/suppliers/{supplierId}",
    operationId: "procurement.getSupplier",
    summary: "Supplier detail",
    tag: "procurement",
    permissions: ["suppliers.view"],
    dataKey: "supplier",
  }),
  operation({
    method: "patch",
    path: "/procurement/suppliers/{supplierId}",
    operationId: "procurement.updateSupplier",
    summary: "Update a supplier",
    tag: "procurement",
    permissions: ["suppliers.update"],
    body: procurement.updateSupplierSchema,
    dataKey: "supplier",
  }),
  operation({
    method: "get",
    path: "/procurement/suppliers/{supplierId}/statement",
    operationId: "procurement.statement",
    summary: "Supplier statement, cursor-paged with balances",
    tag: "procurement",
    permissions: ["supplier_balances.view"],
    query: procurement.statementQuerySchema,
    statement: true,
  }),
  operation({
    method: "get",
    path: "/procurement/purchases",
    operationId: "procurement.listPurchases",
    summary: "Purchases",
    tag: "procurement",
    permissions: ["purchases.view"],
    query: procurement.purchaseListQuerySchema,
    list: true,
  }),
  operation({
    method: "post",
    path: "/procurement/purchases",
    operationId: "procurement.createPurchase",
    summary: "Create a draft purchase",
    tag: "procurement",
    permissions: ["purchases.create"],
    body: procurement.createPurchaseSchema,
    status: 201,
    dataKey: "purchase",
  }),
  operation({
    method: "get",
    path: "/procurement/purchases/{purchaseId}",
    operationId: "procurement.getPurchase",
    summary: "Purchase detail with payment state",
    tag: "procurement",
    permissions: ["purchases.view"],
    dataKey: "purchase",
  }),
  operation({
    method: "post",
    path: "/procurement/purchases/{purchaseId}/post",
    operationId: "procurement.postPurchase",
    summary: "Post a purchase into stock and the supplier ledger",
    tag: "procurement",
    permissions: ["purchases.post"],
    idempotent: true,
    status: 201,
    dataKey: "purchase",
  }),
  operation({
    method: "post",
    path: "/procurement/purchases/{purchaseId}/cancel",
    operationId: "procurement.cancelPurchase",
    summary: "Cancel a purchase",
    tag: "procurement",
    permissions: ["purchases.cancel"],
    body: procurement.cancelPurchaseSchema,
    idempotent: true,
    status: 201,
    dataKey: "purchase",
  }),
  operation({
    method: "get",
    path: "/procurement/supplier-balances",
    operationId: "procurement.listBalances",
    summary: "Supplier balances",
    tag: "procurement",
    permissions: ["supplier_balances.view"],
    query: procurement.supplierBalanceQuerySchema,
    list: true,
  }),
  operation({
    method: "get",
    path: "/procurement/supplier-payments",
    operationId: "procurement.listPayments",
    summary: "Supplier payments",
    tag: "procurement",
    permissions: ["supplier_payments.view"],
    query: procurement.supplierPaymentListQuerySchema,
    list: true,
  }),
  operation({
    method: "post",
    path: "/procurement/supplier-payments",
    operationId: "procurement.createPayment",
    summary: "Record a supplier payment",
    tag: "procurement",
    permissions: ["supplier_payments.create"],
    body: procurement.createSupplierPaymentSchema,
    idempotent: true,
    status: 201,
    dataKey: "payment",
  }),
];

const simulationOperations: ApiOperation[] = [
  operation({
    method: "get",
    path: "/cost-simulations",
    operationId: "simulations.list",
    summary: "Cost simulations",
    tag: "simulations",
    permissions: ["simulations.view"],
    query: simulation.pageQuerySchema,
    list: true,
  }),
  operation({
    method: "post",
    path: "/cost-simulations",
    operationId: "simulations.create",
    summary: "Create a cost simulation",
    tag: "simulations",
    permissions: ["simulations.create"],
    body: simulation.simulationBodySchema,
    status: 201,
    dataKey: "simulation",
  }),
  operation({
    method: "get",
    path: "/cost-simulations/{simulationId}",
    operationId: "simulations.get",
    summary: "Simulation detail",
    tag: "simulations",
    permissions: ["simulations.view"],
    dataKey: "simulation",
  }),
  operation({
    method: "post",
    path: "/cost-simulations/{simulationId}/duplicate",
    operationId: "simulations.duplicate",
    summary: "Duplicate a simulation",
    tag: "simulations",
    permissions: ["simulations.create"],
    body: simulation.duplicateSchema,
    status: 201,
    dataKey: "simulation",
  }),
  operation({
    method: "patch",
    path: "/cost-simulations/{simulationId}",
    operationId: "simulations.update",
    summary: "Update a simulation",
    tag: "simulations",
    permissions: ["simulations.update"],
    body: simulation.updateSimulationSchema,
    dataKey: "simulation",
  }),
  operation({
    method: "delete",
    path: "/cost-simulations/{simulationId}",
    operationId: "simulations.delete",
    summary: "Delete a simulation",
    tag: "simulations",
    permissions: ["simulations.delete"],
    dataKey: "deleted",
  }),
];

export const apiOperations: readonly ApiOperation[] = [
  ...healthOperations,
  ...authOperations,
  ...homeOperations,
  ...accessOperations,
  ...auditOperations,
  ...catalogOperations,
  ...inventoryOperations,
  ...procurementOperations,
  ...posOperations,
  ...customerOperations,
  ...orderOperations,
  ...distributionOperations,
  ...expenseOperations,
  ...simulationOperations,
];
